version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_install:
      - pip install poetry
      - poetry config virtualenvs.create false
    post_install:
      - poetry install --extras docs
      # Ensure key Sphinx extensions are present even if Poetry/extras resolution misbehaves
      - pip install myst-parser sphinx-design sphinx-rtd-theme

sphinx:
  configuration: docs/source/conf.py
