version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    pre_install:
      - pip install poetry
      - poetry config virtualenvs.create false
    post_install:
      - poetry install --with docs
      - pip install sphinx-rtd-theme
      - python -c "import sphinx_rtd_theme; print('sphinx-rtd-theme version:', sphinx_rtd_theme.__version__)"

sphinx:
  configuration: docs/source/conf.py 