name: "Template Debugging Project"
version: "1.0.0"
description: "Example configuration for template debugging"

settings:
  debug_mode: true
  log_level: "info"
  max_file_size: "10MB"
  timeout: 30

features:
  - template_expansion
  - optimization_tracking
  - context_inspection
  - step_debugging

database:
  host: "localhost"
  port: 5432
  name: "debug_db"
  pool_size: 10

api:
  base_url: "https://api.example.com"
  version: "v1"
  rate_limit: 1000

security:
  encryption: true
  auth_required: true
  session_timeout: 3600
