# Notification Service Configuration
# Handles all types of notifications (email, SMS, push)

imports:
  - ../../shared/common.yaml

service:
  name: notification-service
  version: 1.8.0
  description: Multi-channel Notification Service

server:
  host: 0.0.0.0
  port: ${PORT:-8020}
  grpc_port: ${GRPC_PORT:-8021}

providers:
  email:
    primary:
      type: sendgrid
      api_key: ${SENDGRID_API_KEY}
      from_email: ${FROM_EMAIL:-noreply@example.com}
      from_name: ${FROM_NAME:-MyApp}
    fallback:
      type: aws-ses
      region: ${AWS_REGION:-us-west-2}
      access_key_id: ${AWS_ACCESS_KEY_ID}
      secret_access_key: ${AWS_SECRET_ACCESS_KEY}

  sms:
    primary:
      type: twilio
      account_sid: ${TWILIO_ACCOUNT_SID}
      auth_token: ${TWILIO_AUTH_TOKEN}
      from_number: ${TWILIO_FROM_NUMBER}
    fallback:
      type: aws-sns
      region: ${AWS_REGION:-us-west-2}

  push:
    providers:
      - type: firebase
        credentials_file: /etc/credentials/firebase.json
        project_id: ${FIREBASE_PROJECT_ID}
      - type: apns
        key_id: ${APNS_KEY_ID}
        team_id: ${APNS_TEAM_ID}
        private_key_path: /etc/credentials/apns.p8

templates:
  storage:
    type: postgresql
    connection_string: ${TEMPLATE_DB_URL}

  cache:
    type: redis
    url: ${TEMPLATE_REDIS_URL}
    ttl: 1h

queues:
  processor:
    type: redis
    url: ${QUEUE_REDIS_URL}
    concurrency: 50
    rate_limit:
      enabled: true
      per_second: 100

  dead_letter:
    enabled: true
    max_retries: 3
    ttl: 72h

rate_limits:
  email:
    per_user:
      window: 24h
      max_sends: 100
    global:
      window: 1m
      max_sends: 1000

  sms:
    per_user:
      window: 24h
      max_sends: 10
    global:
      window: 1m
      max_sends: 100

  push:
    per_user:
      window: 1h
      max_sends: 50
    global:
      window: 1m
      max_sends: 5000

events:
  consumer:
    type: kafka
    brokers: ${KAFKA_BROKERS}
    group_id: notification-service
    topics:
      - user.created
      - order.status_changed
      - payment.succeeded
      - payment.failed

monitoring:
  health_check:
    enabled: true
    path: /health
    include_dependencies: true
  metrics:
    path: /metrics
    labels:
      service: notification
      component: messaging
  alerts:
    error_rate_threshold: 0.05
    delivery_delay_threshold: 30s
