# Production Environment Configuration

app:
  name: my-service
  version: 1.0.0
  debug: false
  log_level: INFO

database:
  host: ${DB_HOST}
  port: 5432
  name: myapp_prod
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  pool:
    min_size: 10  # Inconsistent with dev (5)
    max_size: 50  # Significantly different from dev (20)
    idle_timeout: 5m  # Different from dev (10m)

cache:
  redis:
    host: ${REDIS_HOST}
    port: 6379
    timeout: 10s  # Inconsistent with dev (30s)

api:
  base_url: https://api.example.com
  rate_limit:
    enabled: true
    max_requests: 1000  # 10x higher than dev without explanation
    window: 1m

security:
  jwt:
    secret: ${JWT_SECRET}
    expiry: 12h  # Different from dev (24h)
  cors:
    allowed_origins:
      - https://example.com
      - https://admin.example.com

monitoring:
  enabled: true
  metrics_port: 9090
  health_check: /healthz  # Inconsistent path with dev (/health)
