name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write  # Required for trusted publishing
      contents: write  # Required for uploading release assets

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Configure Poetry
      run: |
        poetry config virtualenvs.create false

    - name: Install dependencies
      run: |
        poetry install --no-interaction

    - name: Generate installation script
      run: |
        make build-install-script

    - name: Upload installation script to release
      uses: softprops/action-gh-release@v2
      with:
        files: scripts/generated/install-macos.sh

    - name: Build package
      run: |
        poetry build

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
