name: Create Release and Build Binaries

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build_binaries:
    name: Build binaries for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.12']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install .

      - name: Build binary
        run: pyinstaller pyinstaller.spec
      - name: List dist directory (debug)
        run: ls -l dist
        shell: bash
      - name: Rename output directory for Windows
        if: runner.os == 'Windows'
        run: mv dist/ostruct dist/ostruct-windows-amd64
        shell: bash
      - name: Rename output directory for macOS
        if: runner.os == 'macOS'
        run: mv dist/ostruct dist/ostruct-macos-amd64
        shell: bash
      - name: Rename output directory for Linux
        if: runner.os == 'Linux'
        run: mv dist/ostruct dist/ostruct-linux-amd64
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ostruct-bundle-${{ matrix.os }}
          path: dist/ostruct-*

  create_release:
    name: Create GitHub Release
    needs: build_binaries
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: ostruct-bundle-ubuntu-latest
          path: dist/binaries/linux

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: ostruct-bundle-macos-latest
          path: dist/binaries/macos

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: ostruct-bundle-windows-latest
          path: dist/binaries/windows

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG }}
          release_name: Release ${{ env.TAG }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/binaries/linux/ostruct-linux-amd64
          asset_name: ostruct-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload macOS Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/binaries/macos/ostruct-macos-amd64
          asset_name: ostruct-macos-amd64
          asset_content_type: application/octet-stream

      - name: Upload Windows Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/binaries/windows/ostruct-windows-amd64.exe
          asset_name: ostruct-windows-amd64.exe
          asset_content_type: application/octet-stream

  build_and_push_docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get tag
        id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.TAG }}
            ghcr.io/${{ github.repository }}:latest

  update_homebrew_formula:
    name: Update Homebrew Formula
    needs: create_release
    runs-on: macos-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          # Use a personal access token with write permissions
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Set Release Version
        id: get_version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Update pyproject.toml and poetry.lock
        run: |
          poetry version ${{ env.RELEASE_VERSION }}
        # This will update pyproject.toml and poetry.lock with the new version

      - name: Download release tarball
        run: |
          VERSION="${{ env.RELEASE_VERSION }}"
          curl -sL "https://github.com/${{ github.repository }}/archive/refs/tags/v$VERSION.tar.gz" -o "ostruct-v$VERSION.tar.gz"

      - name: Calculate SHA256
        id: shasum
        run: |
          echo "sha256=$(shasum -a 256 "ostruct-v${{ env.RELEASE_VERSION }}.tar.gz" | awk '{print $1}')" >> $GITHUB_ENV

      - name: Update Homebrew Formula
        run: |
          VERSION="${{ env.RELEASE_VERSION }}"
          SHA256="${{ env.sha256 }}"
          FORMULA_FILE="Formula/ostruct-cli.rb"

          # Update version and sha256 in the formula
          sed -i.bak "s|url \".*\"|url \"https://github.com/${{ github.repository }}/archive/refs/tags/v$VERSION.tar.gz\"|" "$FORMULA_FILE"
          sed -i.bak "s|sha256 \".*\"|sha256 \"$SHA256\"|" "$FORMULA_FILE"

          # Remove backup file created by sed, compatible with both macOS and Linux
          rm -f "$FORMULA_FILE.bak"

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add Formula/ostruct-cli.rb pyproject.toml poetry.lock
          git commit -m "chore(release): update Homebrew formula for v${{ env.RELEASE_VERSION }}"
          git push origin main
